/*
 * Copyright (C) 2026 Sami Saubion
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

// Package cmd is the package containing all CLI's commands, it is generated by the Cobra library
package cmd

import (
	"fmt"
	"goralys-cli/utils"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// backupCmd represents the backup command
var backupCmd = &cobra.Command{
	Use:   "backup",
	Short: "A brief description of your command",
	Long: `A longer description that spans multiple lines and likely contains examples
and usage of using your command. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.`,
	RunE: func(_ *cobra.Command, _ []string) error {
		var name = "Goralys"
		var suffix = "frontend"
		if mobileFlag {
			name = "GoralysCap"
		}
		if backendFlag {
			suffix = "backend"
		}

		backupPath, err := utils.FromHomeDir(GoralysBackupDir...)
		if err != nil {
			return fmt.Errorf("failed to construct the backup path, %w", err)
		}

		backupPath = filepath.Join(backupPath, strings.ToLower(name), strings.ToLower(suffix))
		utils.Logf("Creating backup for %s", name)
		utils.Log(utils.Colorize(utils.ColorYellow, "This command does not back up the database"))

		stop := utils.StartSpinner("Finding repo root")

		cwd, err := os.Getwd()
		if err != nil {
			stop(false)
			return fmt.Errorf("failed to get wd, %s", err)
		}

		root, err := utils.FindRepoRoot(cwd, mobileFlag)
		if err != nil {
			stop(false)
			return fmt.Errorf("backup failed, %s", err)
		}

		stop(true)
		utils.Logf("Found, creating backup for repo at %s", root)

		stop = utils.StartSpinner("Checking for existing backup at " + backupPath)
		exists, err := utils.DirExists(backupPath)
		if err != nil {
			stop(false)
			return err
		}
		stop(exists)

		var overwrite = true
		if exists {
			utils.PromptBool(&overwrite, "An existing backup was found, do you want to overwrite ?")
		}

		if !overwrite {
			utils.Log("Aborting backup")
			return nil
		}

		if exists {
			stop = utils.StartSpinner("Removing old backup")
			err = utils.RmAllExcept(backupPath) // keep nothing
			if err != nil {
				stop(false)
				return fmt.Errorf("failed to remove old backup, %w", err)
			}
			stop(true)
		}

		utils.Log("Creating backup")
		stop = utils.StartSpinnerNoPrefix("-> Copying env files")
		err = utils.CopyFile(root, backupPath, ".env.local")
		if err != nil {
			stop(false)
			return err
		}

		err = utils.CopyFile(root, backupPath, filepath.Join("backend", ".env"))
		if err != nil {
			stop(false)
			return err
		}
		stop(true)

		stop = utils.StartSpinnerNoPrefix("-> Copying backend/Assets")
		err = utils.Cp(filepath.Join(root, "backend", "Assets"), filepath.Join(backupPath, "backend", "Assets"))
		if err != nil {
			stop(false)
			return err
		}
		stop(true)

		utils.Log("Backup successfully created")

		return nil
	},
}

func init() {
	rootCmd.AddCommand(backupCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// backupCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// backupCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}
