/*
 * Copyright (C) 2026 Sami Saubion
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

// Package cmd is the package containing all CLI's commands, it is generated by the Cobra library
package cmd

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"goralys-cli/utils"
	templates "goralys-cli/utils/templates"

	"github.com/spf13/cobra"
)

//go:embed templates/dynamic/env.yaml
var envTemplate string

//go:embed templates/dynamic/env.next.yaml
var envNextTemplate string

//go:embed templates/dynamic/env.cap.yaml
var envCapTemplate string

//go:embed templates/static/.htaccess
var htAccessTemplate string

//go:embed templates/static/MainActivity.java
var mainActivityTemplate string

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "This command is used to setup Goralys.",
	Long: `This command is used to create the necessary files and install the
    dependencies (pnpm and composer) for the project.`,
	RunE: func(_ *cobra.Command, _ []string) error {
		var name = "Goralys"
		var suffix = "frontend"
		if mobileFlag {
			name = "GoralysCap"
		}
		if backendFlag {
			suffix = "backend"
		}

		utils.Logf("Setting up %s", name)

		backupPath, err := utils.FromHomeDir(GoralysBackupDir...)
		if err != nil {
			return fmt.Errorf("failed to construct the backup path, %w", err)
		}

		backupPath = filepath.Join(backupPath, strings.ToLower(name), strings.ToLower(suffix))
		stop := utils.StartSpinner("Finding repo root")

		cwd, err := os.Getwd()
		if err != nil {
			stop(false)
			return fmt.Errorf("failed to get wd, %s", err)
		}

		root, err := utils.FindRepoRoot(cwd, mobileFlag)
		if err != nil {
			stop(false)
			return fmt.Errorf("setup failed, %s", err)
		}

		stop(true)
		utils.Logf("Found, setting up for repo at %s", root)

		// backup restore
		stop = utils.StartSpinner("Checking for existing backup at " + backupPath)
		exists, err := utils.DirExists(backupPath)
		if err != nil {
			stop(false)
			return err
		}
		stop(true)

		var restore bool
		if exists {
			utils.PromptBool(&restore, "An existing backup was found, do you want to restore it ?")
		}

		if restore {
			utils.Logf("Restoring backup from %s", backupPath)

			stop = utils.StartSpinnerNoPrefix("-> Copying env files")
			if !backendFlag {
				err = utils.CopyFile(backupPath, root, ".env.local")
				if err != nil {
					stop(false)
					return err
				}
			}
			if !mobileFlag {
				err = utils.CopyFile(backupPath, root, filepath.Join("backend", ".env"))
				if err != nil {
					stop(false)
					return err
				}
			}
			stop(true)

			if !mobileFlag {
				stop = utils.StartSpinnerNoPrefix("-> Copying backend/Assets")
				err = utils.Cp(filepath.Join(backupPath, "backend", "Assets"), filepath.Join(root, "backend", "Assets"))
				if err != nil {
					stop(false)
					return err
				}
				stop(true)
			}

			utils.Log("Backup successfully restored")
		}

		if !backendFlag {
			stop := utils.StartSpinner("Checking for pnpm")
			pnpm, err := utils.ResolvePnpm("install", "--color")
			if err != nil {
				stop(false)
				return fmt.Errorf("failed to find pnpm, %s", err)
			}
			stop(true)

			pnpm.Stdout = utils.NewPrefixWriter("pnpm", os.Stdout)
			pnpm.Stderr = utils.NewPrefixWriter("pnpm", os.Stderr)
			if err = pnpm.Run(); err != nil {
				return fmt.Errorf("failed to run pnpm, %s", err)
			}

			utils.Log("pnpm dependencies installed")
		}

		if !mobileFlag {
			stop := utils.StartSpinner("Checking for composer")
			php, err := utils.ResolvePhp()
			if err != nil {
				stop(false)
				return fmt.Errorf("failed to find php, %s", err)
			}
			stop(true)

			composer, err := utils.ResolveComposer(php, "install", "--working-dir=backend", "--ansi")
			if err != nil {
				return fmt.Errorf("failed to find composer, %s", err)
			}

			composer.Stdout = utils.NewPrefixWriter("composer", os.Stdout)
			composer.Stderr = utils.NewPrefixWriter("composer", os.Stderr)
			if err := composer.Run(); err != nil {
				return fmt.Errorf("failed to run composer, %s", err)
			}

			utils.Log("Composer dependencies installed.")

			err = utils.CreateBackendDirs(root)
			if err != nil {
				return err
			}
		}

		utils.Log("Configuring environments")

		if !mobileFlag {
			utils.Log("(1/2) Creating .env")
			err = templates.MakeEnvFileFromTemplate(root, envTemplate)
			if err != nil {
				return err
			}

			utils.Log("(2/2) Creating .env.local")
			err = templates.MakeEnvFileFromTemplate(root, envNextTemplate)
			if err != nil {
				return err
			}
		} else {
			utils.Log("Creating .env.local")
			err = templates.MakeEnvFileFromTemplate(root, envCapTemplate)
			if err != nil {
				return err
			}
		}

		if backendFlag || mobileFlag {
			utils.Log("Finalizing your configuration, you are almost there")
			if backendFlag {
				stop := utils.StartSpinnerNoPrefix("-> Creating .htaccess")
				err := templates.LoadStaticTemplate(htAccessTemplate, filepath.Join(root, ".htaccess"))
				if err != nil {
					stop(false)
					return err
				}
				stop(true)
			}

			if mobileFlag {
				stop := utils.StartSpinnerNoPrefix("-> Generating assets")
				pnpmGenerate, err := utils.ResolvePnpm("run", "assets:generate")
				if err != nil {
					stop(false)
					return err
				}

				if err = pnpmGenerate.Run(); err != nil {
					stop(false)
					return err
				}
				stop(true)

				stop = utils.StartSpinnerNoPrefix("-> Building project")
				pnpmBuild, err := utils.ResolvePnpm("run", "build")
				if err != nil {
					stop(false)
					return err
				}

				if err = pnpmBuild.Run(); err != nil {
					stop(false)
					return err
				}
				stop(true)

				androidExists, err := utils.DirExists(filepath.Join(root, "android"))
				if err != nil {
					return err
				}

				capCmdTxt := "add"
				if androidExists {
					capCmdTxt = "sync"
				}

				stop = utils.StartSpinnerNoPrefix("-> Setting up capacitor")
				capCmd, err := utils.ResolveNpx("cap", capCmdTxt, "android")
				if err != nil {
					stop(false)
					return err
				}

				if err = capCmd.Run(); err != nil {
					stop(false)
					return err
				}
				stop(true)

				stop = utils.StartSpinnerNoPrefix("-> Creating MainActivity.java")
				err = templates.LoadStaticTemplate(
					mainActivityTemplate,
					filepath.Join(
						root,
						"android",
						"app",
						"src",
						"main",
						"java",
						"fr",
						"goralys",
						"app",
						"MainActivity.java",
					),
				)
				if err != nil {
					stop(false)
					return err
				}
				stop(true)
			}
		}

		if backendFlag {
			utils.Log("Backend only setup detected, removing non backend dir")
			err = utils.RemoveNonBackendDirs(root)
			if err != nil {
				return err
			}
		}

		var testsStr = "eslint + phpcs"
		if mobileFlag {
			testsStr = "eslint"
		} else if backendFlag {
			testsStr = "phpcs"
		}

		var tests bool
		utils.PromptfBool(&tests, "Do you want the setup to run checks (%s) ?", testsStr)

		if tests {
			stop := utils.StartSpinner("Running phpcs")
			err = utils.RunPhpCS()
			if err != nil {
				stop(false)

				var reRun bool
				utils.PromptBool(&reRun, "phpcs violations were found, do you want setup to try to fix them ?")

				if reRun {
					stop = utils.StartSpinner("Running phpcbf")
					if err = utils.RunPhpCBF(); err != nil {
						stop(false)
						return err
					}
					stop(true)

					stop = utils.StartSpinner("Re-running phpcs after fixes")
					if err = utils.RunPhpCS(); err != nil {
						stop(false)
						return err
					}
					stop(true)
					utils.Log("phpcs clean after fixes")
				}
			} else {
				stop(true)
			}

			stop = utils.StartSpinner("Running eslint")
			if err = utils.RunEslint(); err != nil {
				stop(false)
				return err
			}
			stop(true)
		}

		return nil
	},
}

func init() {
	rootCmd.AddCommand(setupCmd)
	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// setupCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// setupCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}
